### ISSUE TITLE
Integrate to Personal Ambient Weather Station

### ISSUE THREAD

**Issue by Thesourceminer** [bramkragten/weather-card#120]
I would love to have my own weather station showing stats on this card is there any way to add the sensors in HA to each component (IE: wind speed, temp, precipitation, humidity etc)

**Comment by austinbeam** [comment]
@Thesourceminer This can be done fairly easily with a [template weather provider](https://www.home-assistant.io/integrations/weather.template/). Then just use your template weather provider as the entity for this card as opposed to using the built-in provider. This is what I've done and it has worked quite well for me. Good luck!

_Note: I found that the ecobee weather provider was a better base for me than the built-in provider, but this is personal preference._

```
weather:
  - platform: template
    name: "Custom Weather"
    condition_template: "{{ states('weather.ecobee') }}"
    temperature_template: "{{ states('sensor.ambient_temp') | float}}"
    humidity_template: "{{ states('sensor.ambient_humidity') | float}}"
    pressure_template: "{{ states('sensor.ambient_abs_pressure') | float}}"
    forecast_template: "{{ state_attr('weather.ecobee', 'forecast') }}"
    wind_speed_template: "{{ states('sensor.ambient_wind_speed') | float}}"
    wind_bearing_template: "{{ states('sensor.ambient_wind_dir') | float}}"
    visibility_template: "{{ state_attr('weather.ecobee', 'visibility') }}"
```
