### ISSUE TITLE
Entity not available: openweathermap

### ISSUE THREAD

**Issue by mikebgrep** [bramkragten/weather-card#147]
I got this error.
My ui-lovelace.yaml.

```
resources:
  - url: /local/weather_card/weather-card.js
    type: module

views:
  - title: Weather
    cards:
      - type: "custom:weather-card"
        entity: weather.openweathermap
        name: 'Wheater'
        icons: "/local/weather_card/icons/"
        current: true
        details: false
        forecast: true
        hourly_forecast: false
        number_of_forecasts: 5
``

My configurations:
```
weather:
  - platform: openweathermap
    api_key: "API_KEY" ## I try and without quotes
```
everything is in `www` folder.Any clue what is wrong or the card is not working.
