### ISSUE TITLE
[Feature Request] Make weather.com entity data compatible with Card

### ISSUE THREAD

**Issue by Dvalin21** [bramkragten/weather-card#162]
Currently, I can get basic info to the card, however
daily and hourly forecast update will not show unless I click on the card itself. 

![Card](https://github.com/bramkragten/weather-card/assets/7469013/0880ee9c-7235-4896-b94d-ec717f39cc6f)
![Card extended](https://github.com/bramkragten/weather-card/assets/7469013/d74e4f02-6c80-4071-9f87-fce6959ac309)
![card settings](https://github.com/bramkragten/weather-card/assets/7469013/1a81e489-e478-4b91-b8ef-2ff5d2ed211d)

```
type: custom:weather-card
entity: weather.house_of_god_3
current: true
details: true
forecast: true
hourly_forecast: true
number_of_forecasts: 5
resources:
  - url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
```
I'm using the Weather.com (WeatherChannel) integration.
