### ISSUE TITLE
"forecast: true" not working anymore for `weather.openweathermap`

### ISSUE THREAD

**Issue by mkanet** [bramkragten/weather-card#174]
It looks like there were some changes to `weather.openweathermap` recently.  The native home assistant water card was smart enough to continue displaying forecast days correctly.  However, the animated weather card only displays current weather for today.  See below:

**weather-card**
```yaml
type: custom:weather-card
entity: weather.openweathermap
current: true
details: false
forecast: true
hourly_forecast: false
```
![image](https://github.com/bramkragten/weather-card/assets/811008/3381e50b-8475-48fa-8065-e8e2c9ae4590)

**weather-forecast**
```yaml
type: weather-forecast
entity: weather.openweathermap
forecast_type: daily
```
![image](https://github.com/bramkragten/weather-card/assets/811008/3b6cad30-0320-4665-bfec-d87575668d00)

![image](https://github.com/bramkragten/weather-card/assets/811008/e2d7d7e2-c963-44ae-9f2d-121d5dbdd8fb)
