### ISSUE TITLE
Forecast not showing

### ISSUE THREAD

**Issue by Triskelen** [bramkragten/weather-card#180]
the card does not show the forecast, how can i fix this?

```yaml
  - type: custom:weather-card
    entity: weather.forecast_thuis
    forecast: true
    current: true
    details: false
    hourly_forecast: false
```
