### ISSUE TITLE
How to configure yourweatherentity

### ISSUE THREAD

**Issue by jpljonkman** [bramkragten/weather-card#2]
Perhaps to easy but I don't see it.

What to use for (entity: weather.)yourweatherentity? I've tried everything, various entities from Darksky, the platform name etc. All responding "entity not available: xx"

**Comment by fribse** [comment]
I just have my smhi sensor set up, and give that, that work perfectly.
Are you sure you have set up a darksky sensor?

**Comment by bramkragten** [comment]
You need to setup the darksky weather platform:

```yaml
# Example configuration.yaml entry
weather:
  - platform: darksky
    api_key: YOUR_API_KEY
    mode: daily
```
