### ISSUE TITLE
Custom element doesn't exist: weather-card

### ISSUE THREAD

**Issue by chezpaul** [bramkragten/weather-card#28]
This is the error I get in my lovelace UI.

This is my ui-lovelace code:
```
resources:
- url: /local/custom-lovelace/weather-card/weather-card.js
  type: module

cards:
  - type: custom:weather-card
    entity: weather.dark_sky
    icons: "/local/custom-lovelace/weather-card/icons/"
    current: true
    details: false
    forecast: true
```
The weather-card.js is the latest downloaded the raw version from github.
My config:
```
#DARKSKY
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
```

js file and icon folder are both in www/custom-lovelace/weather-card

Am I doing anything wrong?
