### ISSUE TITLE
Feature request: Days

### ISSUE THREAD

**Issue by oz9els** [bramkragten/weather-card#36]
first of all, the card looks GREAT...

Would it be possible to have a setting saying:

Days: 4 
to only have 4 days forecast ??

**Comment by schmacka** [comment]
I'd be interested in this feature too! I'd be happy with 3 days

**Comment by ChrisRomp** [comment]
Set the `number_of_forecasts` parameter.

Example:
```yaml
- type: custom:weather-card
  entity: weather.dark_sky
  number_of_forecasts: 3
```

Result:
![image](https://user-images.githubusercontent.com/1683889/88949837-a1aa6b00-d248-11ea-8dc2-76d039c963a2.png)
