### ISSUE TITLE
Only Highs - Not Lows

### ISSUE THREAD

**Issue by grossmanns** [bramkragten/weather-card#41]
Even if the mode: daily is set

**Comment by bramkragten** [comment]
That's not a lot of info to go on :-)

**Comment by grossmanns** [comment]
I mean, I see only the High temperatures on the card, and not the Lows. I have this in configuration.yaml :
```
weather:
   - platform: darksky
     api_key: mykey
     mode: daily
```

And this is my card :
`entity: weather.maison
name: Météo
type: 'custom:weather-card'
`

Everything seems nice, but I'd like to have both highs ans lows temperatures.
